version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: all

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      sorbet:
        patterns:
          - "sorbet*"
